"""empty message

Revision ID: 7ef673d55ac2
Revises: 7a7fd1f0daa6
Create Date: 2024-04-25 15:24:02.090703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef673d55ac2'
down_revision = '7a7fd1f0daa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajesfavoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetasfavoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planetas_favoritos')
    op.drop_table('personajes_favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], name='personajes_favoritos_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='personajes_favoritos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personajes_favoritos_pkey')
    )
    op.create_table('planetas_favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], name='planetas_favoritos_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='planetas_favoritos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planetas_favoritos_pkey')
    )
    op.drop_table('planetasfavoritos')
    op.drop_table('personajesfavoritos')
    # ### end Alembic commands ###
