"""empty message

Revision ID: ba24eb7b8ffc
Revises: 25cd76294806
Create Date: 2024-04-24 17:19:00.003971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba24eb7b8ffc'
down_revision = '25cd76294806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('diametro', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('temperatura', sa.String(length=250), nullable=False))
        batch_op.drop_column('peso')
        batch_op.drop_column('raza')
        batch_op.drop_column('altura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altura', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raza', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peso', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('temperatura')
        batch_op.drop_column('diametro')
        batch_op.drop_column('poblacion')

    op.drop_table('planetas_favoritos')
    # ### end Alembic commands ###
